# fly.toml file generated for universal-chat on 2023-03-22T19:29:53+01:00

app = "universal-chat"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RUST_LOG="debug"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 5888
  processes = ["app"]
  protocol = "udp"
  script_checks = []
  [services.concurrency]
    hard_limit = 200
    type = "connections"

  [[services.ports]]
    port = 5888

